/*
 This file is part of Darling.

 Copyright (C) 2020 Lubos Dolezel

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <nw/internal/parameters.h>
#include <nw/internal/stubs.h>

nw_parameters_configure_protocol_block_t _nw_parameters_configure_protocol_default_configuration = ^(nw_protocol_options_t NW_NON_NULL options) {};
nw_parameters_configure_protocol_block_t _nw_parameters_configure_protocol_disable = ^(nw_protocol_options_t NW_NON_NULL options) {};

@implementation _NW_CONCRETE_IMPL(nw_parameters)

DARLING_NW_CLASS_STUB;

@end

DARLING_NW_STUB(nw_parameters_add_protocol_stack_member);
DARLING_NW_STUB(nw_parameters_add_proxy_options);
DARLING_NW_STUB(nw_parameters_add_to_protocol_stack);
DARLING_NW_STUB(nw_parameters_are_compatible);
DARLING_NW_STUB(nw_parameters_are_valid);
DARLING_NW_STUB(nw_parameters_clear_prohibited_interface_types);
DARLING_NW_STUB(nw_parameters_clear_prohibited_interfaces);
DARLING_NW_STUB(nw_parameters_clear_protocol_stack);
DARLING_NW_STUB(nw_parameters_clear_proxy_options);
DARLING_NW_STUB(nw_parameters_copy);
DARLING_NW_STUB(nw_parameters_copy_avoided_netagent_domains);
DARLING_NW_STUB(nw_parameters_copy_avoided_netagent_types);
DARLING_NW_STUB(nw_parameters_copy_avoided_netagent_uuids);
DARLING_NW_STUB(nw_parameters_copy_connected);
DARLING_NW_STUB(nw_parameters_copy_context);
DARLING_NW_STUB(nw_parameters_copy_default_protocol_stack);
DARLING_NW_STUB(nw_parameters_copy_description);
DARLING_NW_STUB(nw_parameters_copy_dictionary);
DARLING_NW_STUB(nw_parameters_copy_effective_proxy_settings);
DARLING_NW_STUB(nw_parameters_copy_initial_data_payload);
DARLING_NW_STUB(nw_parameters_copy_local_address);
DARLING_NW_STUB(nw_parameters_copy_local_endpoint);
DARLING_NW_STUB(nw_parameters_copy_metadata);
DARLING_NW_STUB(nw_parameters_copy_path_parameters);
DARLING_NW_STUB(nw_parameters_copy_preferred_netagent_domains);
DARLING_NW_STUB(nw_parameters_copy_preferred_netagent_types);
DARLING_NW_STUB(nw_parameters_copy_preferred_netagent_uuids);
DARLING_NW_STUB(nw_parameters_copy_prohibited_interface_subtypes);
DARLING_NW_STUB(nw_parameters_copy_prohibited_interface_types);
DARLING_NW_STUB(nw_parameters_copy_prohibited_interfaces);
DARLING_NW_STUB(nw_parameters_copy_prohibited_netagent_domains);
DARLING_NW_STUB(nw_parameters_copy_prohibited_netagent_types);
DARLING_NW_STUB(nw_parameters_copy_prohibited_netagent_uuids);
DARLING_NW_STUB(nw_parameters_copy_protocol_options);
DARLING_NW_STUB(nw_parameters_copy_protocol_options_for_definition);
DARLING_NW_STUB(nw_parameters_copy_protocol_options_legacy);
DARLING_NW_STUB(nw_parameters_copy_protocol_value);
DARLING_NW_STUB(nw_parameters_copy_proxy_configuration);
DARLING_NW_STUB(nw_parameters_copy_required_interface);
DARLING_NW_STUB(nw_parameters_copy_required_netagent_domains);
DARLING_NW_STUB(nw_parameters_copy_required_netagent_types);
DARLING_NW_STUB(nw_parameters_copy_required_netagent_uuids);
DARLING_NW_STUB(nw_parameters_copy_tls_session_id);
DARLING_NW_STUB(nw_parameters_copy_transform_array);
DARLING_NW_STUB(nw_parameters_copy_url_endpoint);
DARLING_NW_STUB(nw_parameters_create);
DARLING_NW_STUB(nw_parameters_create_custom_ip);
DARLING_NW_STUB(nw_parameters_create_empty_stack);
DARLING_NW_STUB(nw_parameters_create_from_dictionary);
DARLING_NW_STUB(nw_parameters_create_legacy_tcp_socket);
DARLING_NW_STUB(nw_parameters_create_protocol_parameters);
DARLING_NW_STUB(nw_parameters_create_quic_connection);
DARLING_NW_STUB(nw_parameters_create_quic_connection_with_tls_fallback);
DARLING_NW_STUB(nw_parameters_create_quic_stream);
DARLING_NW_STUB(nw_parameters_create_quic_stream_with_tls_fallback);
DARLING_NW_STUB(nw_parameters_create_secure_udp);
DARLING_NW_STUB(nw_parameters_get_account_id);
DARLING_NW_STUB(nw_parameters_get_allow_duplicate_state_updates);
DARLING_NW_STUB(nw_parameters_get_allow_joining_connected_fd);
DARLING_NW_STUB(nw_parameters_get_allow_socket_access);
DARLING_NW_STUB(nw_parameters_get_allow_unusable_addresses);
DARLING_NW_STUB(nw_parameters_get_always_open_listener_socket);
DARLING_NW_STUB(nw_parameters_get_attach_protocol_listener);
DARLING_NW_STUB(nw_parameters_get_background_traffic_management);
DARLING_NW_STUB(nw_parameters_get_bundle_id_to_uuid_mapping_failed);
DARLING_NW_STUB(nw_parameters_get_companion_link_upgrade_preference);
DARLING_NW_STUB(nw_parameters_get_companion_preference);
DARLING_NW_STUB(nw_parameters_get_context_privacy_level);
DARLING_NW_STUB(nw_parameters_get_data_mode);
DARLING_NW_STUB(nw_parameters_get_delegated_unique_pid);
DARLING_NW_STUB(nw_parameters_get_desperate_ivan);
DARLING_NW_STUB(nw_parameters_get_discretionary);
DARLING_NW_STUB(nw_parameters_get_dry_run);
DARLING_NW_STUB(nw_parameters_get_e_proc_uuid);
DARLING_NW_STUB(nw_parameters_get_ecn_mode);
DARLING_NW_STUB(nw_parameters_get_effective_audit_token);
DARLING_NW_STUB(nw_parameters_get_effective_bundle_id);
DARLING_NW_STUB(nw_parameters_get_expected_workload);
DARLING_NW_STUB(nw_parameters_get_expired_dns_behavior);
DARLING_NW_STUB(nw_parameters_get_fast_open_enabled);
DARLING_NW_STUB(nw_parameters_get_fast_open_force_enable);
DARLING_NW_STUB(nw_parameters_get_hash);
DARLING_NW_STUB(nw_parameters_get_https_proxy_is_opaque);
DARLING_NW_STUB(nw_parameters_get_https_proxy_over_tls);
DARLING_NW_STUB(nw_parameters_get_ignore_resolver_stats);
DARLING_NW_STUB(nw_parameters_get_include_peer_to_peer);
DARLING_NW_STUB(nw_parameters_get_indefinite);
DARLING_NW_STUB(nw_parameters_get_indefinite_set);
DARLING_NW_STUB(nw_parameters_get_ip_protocol);
DARLING_NW_STUB(nw_parameters_get_is_probe);
DARLING_NW_STUB(nw_parameters_get_keepalive_enabled);
DARLING_NW_STUB(nw_parameters_get_keepalive_idle_time);
DARLING_NW_STUB(nw_parameters_get_keepalive_interval);
DARLING_NW_STUB(nw_parameters_get_keepalive_offload);
DARLING_NW_STUB(nw_parameters_get_local_address_preference);
DARLING_NW_STUB(nw_parameters_get_local_only);
DARLING_NW_STUB(nw_parameters_get_maximum_tls_protocol_version);
DARLING_NW_STUB(nw_parameters_get_minimum_tls_protocol_version);
DARLING_NW_STUB(nw_parameters_get_multipath);
DARLING_NW_STUB(nw_parameters_get_multipath_force_enable);
DARLING_NW_STUB(nw_parameters_get_multipath_service);
DARLING_NW_STUB(nw_parameters_get_no_cellular_fallback);
DARLING_NW_STUB(nw_parameters_get_no_delay);
DARLING_NW_STUB(nw_parameters_get_no_fallback);
DARLING_NW_STUB(nw_parameters_get_no_fullstack_fallback);
DARLING_NW_STUB(nw_parameters_get_no_opaque_proxy);
DARLING_NW_STUB(nw_parameters_get_no_proxy);
DARLING_NW_STUB(nw_parameters_get_no_proxy_path_selection);
DARLING_NW_STUB(nw_parameters_get_no_transform);
DARLING_NW_STUB(nw_parameters_get_only_primary_requires_type);
DARLING_NW_STUB(nw_parameters_get_parent_id);
DARLING_NW_STUB(nw_parameters_get_pid);
DARLING_NW_STUB(nw_parameters_get_pid_to_uuid_mapping_failed);
DARLING_NW_STUB(nw_parameters_get_prefer_no_proxy);
DARLING_NW_STUB(nw_parameters_get_proc_uuid);
DARLING_NW_STUB(nw_parameters_get_prohibit_cellular);
DARLING_NW_STUB(nw_parameters_get_prohibit_constrained);
DARLING_NW_STUB(nw_parameters_get_prohibit_expensive);
DARLING_NW_STUB(nw_parameters_get_prohibit_joining_protocols);
DARLING_NW_STUB(nw_parameters_get_prohibit_roaming);
DARLING_NW_STUB(nw_parameters_get_protocol_count);
DARLING_NW_STUB(nw_parameters_get_proxy_bundle_id);
DARLING_NW_STUB(nw_parameters_get_receive_any_interface);
DARLING_NW_STUB(nw_parameters_get_reduce_buffering);
DARLING_NW_STUB(nw_parameters_get_required_address_family);
DARLING_NW_STUB(nw_parameters_get_required_interface_index);
DARLING_NW_STUB(nw_parameters_get_required_interface_subtype);
DARLING_NW_STUB(nw_parameters_get_required_interface_type);
DARLING_NW_STUB(nw_parameters_get_resolve_ptr);
DARLING_NW_STUB(nw_parameters_get_reuse_local_address);
DARLING_NW_STUB(nw_parameters_get_sanitized_url);
DARLING_NW_STUB(nw_parameters_get_self_bundle_id);
DARLING_NW_STUB(nw_parameters_get_server_mode);
DARLING_NW_STUB(nw_parameters_get_service_class);
DARLING_NW_STUB(nw_parameters_get_should_skip_probe_sampling);
DARLING_NW_STUB(nw_parameters_get_should_trust_invalid_certificates);
DARLING_NW_STUB(nw_parameters_get_sleep_keepalive_interval);
DARLING_NW_STUB(nw_parameters_get_ssl_cipher_suites);
DARLING_NW_STUB(nw_parameters_get_tfo);
DARLING_NW_STUB(nw_parameters_get_tfo_no_cookie);
DARLING_NW_STUB(nw_parameters_get_tls);
DARLING_NW_STUB(nw_parameters_get_tls13_enabled);
DARLING_NW_STUB(nw_parameters_get_tls_experiments_enabled);
DARLING_NW_STUB(nw_parameters_get_tls_session_ticket_enabled);
DARLING_NW_STUB(nw_parameters_get_traffic_class);
DARLING_NW_STUB(nw_parameters_get_uid);
DARLING_NW_STUB(nw_parameters_get_upper_transport_protocol);
DARLING_NW_STUB(nw_parameters_get_upper_transport_protocol_options);
DARLING_NW_STUB(nw_parameters_get_url);
DARLING_NW_STUB(nw_parameters_get_use_awdl);
DARLING_NW_STUB(nw_parameters_get_use_long_outstanding_queries);
DARLING_NW_STUB(nw_parameters_get_use_p2p);
DARLING_NW_STUB(nw_parameters_get_use_tfo_heuristics);
DARLING_NW_STUB(nw_parameters_has_delegated_proc_pid);
DARLING_NW_STUB(nw_parameters_has_delegated_proc_uuid);
DARLING_NW_STUB(nw_parameters_has_initial_data_payload);
DARLING_NW_STUB(nw_parameters_has_non_empty_proxy_configuration);
DARLING_NW_STUB(nw_parameters_has_preferred_netagents);
DARLING_NW_STUB(nw_parameters_has_prohibited_interface_subtypes);
DARLING_NW_STUB(nw_parameters_has_prohibited_interface_types);
DARLING_NW_STUB(nw_parameters_has_prohibited_interfaces);
DARLING_NW_STUB(nw_parameters_has_prohibited_netagents);
DARLING_NW_STUB(nw_parameters_has_protocol_at_level);
DARLING_NW_STUB(nw_parameters_has_protocol_in_stack);
DARLING_NW_STUB(nw_parameters_has_required_interface_subtype);
DARLING_NW_STUB(nw_parameters_has_required_interface_type);
DARLING_NW_STUB(nw_parameters_has_required_netagents);
DARLING_NW_STUB(nw_parameters_has_transforms);
DARLING_NW_STUB(nw_parameters_internal_iterate_protocol_stack);
DARLING_NW_STUB(nw_parameters_is_custom_protocols_only);
DARLING_NW_STUB(nw_parameters_is_equal);
DARLING_NW_STUB(nw_parameters_is_fallback);
DARLING_NW_STUB(nw_parameters_iterate_prohibited_interface_types);
DARLING_NW_STUB(nw_parameters_iterate_prohibited_interfaces);
DARLING_NW_STUB(nw_parameters_multipath_fallback_allowed);
DARLING_NW_STUB(nw_parameters_prohibit_interface);
DARLING_NW_STUB(nw_parameters_prohibit_interface_type);
DARLING_NW_STUB(nw_parameters_remove_definition_from_protocol_stack);
DARLING_NW_STUB(nw_parameters_remove_from_protocol_stack);
DARLING_NW_STUB(nw_parameters_set_account_id);
DARLING_NW_STUB(nw_parameters_set_allow_duplicate_state_updates);
DARLING_NW_STUB(nw_parameters_set_allow_joining_connected_fd);
DARLING_NW_STUB(nw_parameters_set_allow_socket_access);
DARLING_NW_STUB(nw_parameters_set_allow_unusable_addresses);
DARLING_NW_STUB(nw_parameters_set_always_open_listener_socket);
DARLING_NW_STUB(nw_parameters_set_attach_protocol_listener);
DARLING_NW_STUB(nw_parameters_set_avoided_netagent_classes);
DARLING_NW_STUB(nw_parameters_set_avoided_netagent_uuids);
DARLING_NW_STUB(nw_parameters_set_background_traffic_management);
DARLING_NW_STUB(nw_parameters_set_companion_link_upgrade_preference);
DARLING_NW_STUB(nw_parameters_set_companion_preference);
DARLING_NW_STUB(nw_parameters_set_context);
DARLING_NW_STUB(nw_parameters_set_custom_protocols_only);
DARLING_NW_STUB(nw_parameters_set_data_mode);
DARLING_NW_STUB(nw_parameters_set_delegated_unique_pid);
DARLING_NW_STUB(nw_parameters_set_desperate_ivan);
DARLING_NW_STUB(nw_parameters_set_discretionary);
DARLING_NW_STUB(nw_parameters_set_dry_run);
DARLING_NW_STUB(nw_parameters_set_ecn_mode);
DARLING_NW_STUB(nw_parameters_set_effective_audit_token);
DARLING_NW_STUB(nw_parameters_set_effective_bundle_id);
DARLING_NW_STUB(nw_parameters_set_effective_proxy_settings);
DARLING_NW_STUB(nw_parameters_set_expected_workload);
DARLING_NW_STUB(nw_parameters_set_expired_dns_behavior);
DARLING_NW_STUB(nw_parameters_set_fast_open_enabled);
DARLING_NW_STUB(nw_parameters_set_fast_open_force_enable);
DARLING_NW_STUB(nw_parameters_set_https_proxy_is_opaque);
DARLING_NW_STUB(nw_parameters_set_https_proxy_over_tls);
DARLING_NW_STUB(nw_parameters_set_ignore_resolver_stats);
DARLING_NW_STUB(nw_parameters_set_include_peer_to_peer);
DARLING_NW_STUB(nw_parameters_set_initial_data_payload);
DARLING_NW_STUB(nw_parameters_set_is_fallback);
DARLING_NW_STUB(nw_parameters_set_is_probe);
DARLING_NW_STUB(nw_parameters_set_keepalive_enabled);
DARLING_NW_STUB(nw_parameters_set_keepalive_idle_time);
DARLING_NW_STUB(nw_parameters_set_keepalive_interval);
DARLING_NW_STUB(nw_parameters_set_keepalive_offload);
DARLING_NW_STUB(nw_parameters_set_local_address);
DARLING_NW_STUB(nw_parameters_set_local_address_preference);
DARLING_NW_STUB(nw_parameters_set_local_endpoint);
DARLING_NW_STUB(nw_parameters_set_local_only);
DARLING_NW_STUB(nw_parameters_set_maximum_tls_protocol_version);
DARLING_NW_STUB(nw_parameters_set_metadata);
DARLING_NW_STUB(nw_parameters_set_minimum_tls_protocol_version);
DARLING_NW_STUB(nw_parameters_set_multipath);
DARLING_NW_STUB(nw_parameters_set_multipath_force_enable);
DARLING_NW_STUB(nw_parameters_set_multipath_service);
DARLING_NW_STUB(nw_parameters_set_no_cellular_fallback);
DARLING_NW_STUB(nw_parameters_set_no_delay);
DARLING_NW_STUB(nw_parameters_set_no_fallback);
DARLING_NW_STUB(nw_parameters_set_no_fullstack_fallback);
DARLING_NW_STUB(nw_parameters_set_no_opaque_proxy);
DARLING_NW_STUB(nw_parameters_set_no_proxy);
DARLING_NW_STUB(nw_parameters_set_no_proxy_path_selection);
DARLING_NW_STUB(nw_parameters_set_no_transform);
DARLING_NW_STUB(nw_parameters_set_only_primary_requires_type);
DARLING_NW_STUB(nw_parameters_set_parent_id);
DARLING_NW_STUB(nw_parameters_set_prefer_no_proxy);
DARLING_NW_STUB(nw_parameters_set_preferred_netagent_classes);
DARLING_NW_STUB(nw_parameters_set_preferred_netagent_uuids);
DARLING_NW_STUB(nw_parameters_set_proc_uuid);
DARLING_NW_STUB(nw_parameters_set_prohibit_constrained);
DARLING_NW_STUB(nw_parameters_set_prohibit_expensive);
DARLING_NW_STUB(nw_parameters_set_prohibit_joining_protocols);
DARLING_NW_STUB(nw_parameters_set_prohibit_roaming);
DARLING_NW_STUB(nw_parameters_set_prohibited_interface_subtypes);
DARLING_NW_STUB(nw_parameters_set_prohibited_interface_types);
DARLING_NW_STUB(nw_parameters_set_prohibited_interfaces);
DARLING_NW_STUB(nw_parameters_set_prohibited_netagent_classes);
DARLING_NW_STUB(nw_parameters_set_prohibited_netagent_uuids);
DARLING_NW_STUB(nw_parameters_set_protocol_instance);
DARLING_NW_STUB(nw_parameters_set_protocol_value);
DARLING_NW_STUB(nw_parameters_set_proxy_bundle_id);
DARLING_NW_STUB(nw_parameters_set_proxy_configuration);
DARLING_NW_STUB(nw_parameters_set_receive_any_interface);
DARLING_NW_STUB(nw_parameters_set_reduce_buffering);
DARLING_NW_STUB(nw_parameters_set_required_address_family);
DARLING_NW_STUB(nw_parameters_set_required_interface_subtype);
DARLING_NW_STUB(nw_parameters_set_required_interface_type);
DARLING_NW_STUB(nw_parameters_set_required_netagent_classes);
DARLING_NW_STUB(nw_parameters_set_required_netagent_uuids);
DARLING_NW_STUB(nw_parameters_set_resolve_ptr);
DARLING_NW_STUB(nw_parameters_set_reuse_local_address);
DARLING_NW_STUB(nw_parameters_set_server_mode);
DARLING_NW_STUB(nw_parameters_set_service_class);
DARLING_NW_STUB(nw_parameters_set_should_skip_probe_sampling);
DARLING_NW_STUB(nw_parameters_set_should_trust_invalid_certificates);
DARLING_NW_STUB(nw_parameters_set_sleep_keepalive_interval);
DARLING_NW_STUB(nw_parameters_set_source_application);
DARLING_NW_STUB(nw_parameters_set_source_application_by_bundle_id);
DARLING_NW_STUB(nw_parameters_set_source_application_by_bundle_id_internal);
DARLING_NW_STUB(nw_parameters_set_source_application_by_external_bundle_id);
DARLING_NW_STUB(nw_parameters_set_ssl_cipher_suites);
DARLING_NW_STUB(nw_parameters_set_tfo);
DARLING_NW_STUB(nw_parameters_set_tfo_no_cookie);
DARLING_NW_STUB(nw_parameters_set_tls);
DARLING_NW_STUB(nw_parameters_set_tls13_enabled);
DARLING_NW_STUB(nw_parameters_set_tls_enforce_ev);
DARLING_NW_STUB(nw_parameters_set_tls_experiments_enabled);
DARLING_NW_STUB(nw_parameters_set_tls_session_id);
DARLING_NW_STUB(nw_parameters_set_tls_session_ticket_enabled);
DARLING_NW_STUB(nw_parameters_set_traffic_class);
DARLING_NW_STUB(nw_parameters_set_transform_array);
DARLING_NW_STUB(nw_parameters_set_url);
DARLING_NW_STUB(nw_parameters_set_url_endpoint);
DARLING_NW_STUB(nw_parameters_set_use_awdl);
DARLING_NW_STUB(nw_parameters_set_use_long_outstanding_queries);
DARLING_NW_STUB(nw_parameters_set_use_p2p);
DARLING_NW_STUB(nw_parameters_set_use_tfo_heuristics);

/**
 *
 * ~~~ fixed up stubs ~~~
 *
 */

nw_parameters_t nw_parameters_create_secure_tcp(nw_parameters_configure_protocol_block_t configure_tls, nw_parameters_configure_protocol_block_t configure_tcp) {
	DARLING_NW_STUB_PRINT;
	return NULL;
};

void nw_parameters_set_indefinite(nw_parameters_t parameters, bool value) {
	DARLING_NW_STUB_PRINT;
};

void nw_parameters_set_e_proc_uuid(nw_parameters_t parameters, uuid_t uuid) {
	DARLING_NW_STUB_PRINT;
};

void nw_parameters_set_pid(nw_parameters_t parameters, pid_t pid) {
	DARLING_NW_STUB_PRINT;
};

void nw_parameters_set_uid(nw_parameters_t parameters, uid_t uid) {
	DARLING_NW_STUB_PRINT;
};

void nw_parameters_require_interface(nw_parameters_t parameters, nw_interface_t interface) {
	DARLING_NW_STUB_PRINT;
};
